baseURL: 'https://walkergriggs.com'
languageCode: 'en-us'
title: 'Walker Griggs'
pluralizelisttitles: "false"


params:
        header: Walker Griggs is a video and distributed systems engineer, focused on developer-first platforms. He is based in San Francisco, California.
        footer: "<{Year} * hello@walkergriggs.com>"
        getFormLink: https://getform.io/f/0f0f62d6-edbd-45d9-a998-3e2148260d5d
        formLabel: Want to be forwarded essays as they’re posted?

disableKinds: ["taxonomy"]
ignoreErrors: ["error-disable-taxonomy"]

permalinks:
        posts: "/:year/:month/:day/:filename"
        pages: "/:slug"

menu:
        main:
                - name: Home.
                  url: ""
                  weight: 1
                - name: Posts.
                  url: "posts/"
                  weight: 2
                - name: Projects.
                  url: "https://github.com/WalkerGriggs"
                  weight: 4
                - name: RSS.
                  url: "/index.xml"
                  weight: 5


markup:
        goldmark:
                renderer:
                        unsafe: true
        highlight:
                anchorLineNos: false
                codeFences: true
                guessSyntax: false
                hl_Lines: ""
                hl_inline: false
                lineAnchors: ""
                lineNoStart: 1
                lineNos: false
                lineNumbersInTable: true
                noClasses: true
                noHl: false
                style: dracula
                tabWidth: 4