baseURL = "/"
languageCode = "en-us"
title = "technobabble"
theme = "cactus-lite"

[Author]
  name = "Walker Griggs"

[params]
  author = "Walker Griggs"
  copyright = "Walker Griggs"
  colortheme = "classic"
  mainSection = "posts"
  showAllPostsOnHomePage = true
  tagsOverview = false
  rss = true
  projectsUrl = "https://github.com/walkergriggs"

  [source]
    org_file = "content.org"
    md_dir = "content"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Writings"
    url = "/posts"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "emacs"
    tabWidth = 4
